#!/bin/python
import sys

from config import InteractiveConfigValidation
from network import get_ip


def usage():
    print 'Usage:\b%s <private_domain>\nreturns ip for private domain' % (sys.argv[0],)
    sys.exit(1)

if len(sys.argv) != 2:
    usage()

icv = InteractiveConfigValidation()
icv.run()
config = icv.get()

resp = get_ip(config['server'], config['port'], config['secret'], sys.argv[1])

if resp == 'not_found':
    print 'not found'
elif resp == 'connection_error':
    print 'connection error'
else:
    print resp
