#!/bin/python

import socket
import sys
import requests
import time

SERVER = "http://localhost"
PORT = 5555
SECRET = 'gzkfqqurkvnjtagjfmxi'

def usage():
    print 'Usage:\b%s <private_domain>\nreturns ip for private domain' % (sys.argv[0],)
    sys.exit(1)

if len(sys.argv) < 2:
    usage()

payload = {
    'domain': sys.argv[1],
    'password': SECRET,
}

r = requests.post('%s:%d/get_ip' % (SERVER,PORT), data=payload)
if r.status_code == 404:
    print 'not found'
    sys.exit(2)
elif r.status_code != 200:
    print 'connection error'
else:
    print r.text
